/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'servicesUsed' : Array<string>,
  'category' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'displayOrder' : bigint,
  'description' : string,
  'iconName' : string,
  'category' : string,
}
export interface Submission {
  'projectType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'budget' : string,
}
export interface TeamMember {
  'id' : bigint,
  'bio' : string,
  'displayOrder' : bigint,
  'name' : string,
  'role' : string,
  'imageUrl' : ExternalBlob,
}
export interface Testimonial {
  'id' : bigint,
  'createdAt' : Time,
  'role' : string,
  'text' : string,
  'author' : string,
  'company' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioItem' : ActorMethod<[PortfolioItem], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'addTeamMember' : ActorMethod<[TeamMember], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioItem' : ActorMethod<[bigint], [] | [PortfolioItem]>,
  'getPortfolioItemsByCategory' : ActorMethod<[string], Array<PortfolioItem>>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getTeamMember' : ActorMethod<[bigint], [] | [TeamMember]>,
  'getTestimonial' : ActorMethod<[bigint], [] | [Testimonial]>,
  'getTestimonialsByRating' : ActorMethod<[bigint], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminBeenAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitForm' : ActorMethod<[Submission], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
